# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Notes
tagline:          'An Encyclopedia'
description:      'An Encyclopedia'
url:              https://ludavid15.github.io/
baseurl:          /notes/


author:
  name:           'David Lu'
  url:            

plugins:
  - jekyll-seo-tag

# Google Analytics
google_analytics: G-QF0ZEHWW7Y

paginate:         5

# Custom vars
version:          2.1.0


github:
  repo:           
